### ISSUE TITLE
Returns API Error when there is no error

### ISSUE THREAD

**Issue by jdesmont** [exitround/capital-iq#1]
Example request:

```
client.request_gdsp( ["MSFT"], ["IQ_COMPANY_NAME"] )
```

response is:

```
#<CapitalIQ::RequestResult Headers=["IQ_COMPANY_NAME"], Rows=[{"Row"=>["Microsoft Corporation"]}], NumCols=1, Seniority="", Mnemonic="IQ_COMPANY_NAME", Function="GDSP", ErrMsg="", StartDate="", NumRows=1, CacheExpiryTime="0", SnapType="", Frequency="", Identifier="MSFT", Limit="">
```

which is identified as an Error by the gem because ErrMsg is not nil

I started to get this error today so this may be new CapIQ behavior

**Comment by jdesmont** [comment]
Proposed fix is to change the following in function has_errors? in request_result.rb:

```
!self.ErrMsg.blank?
```

instead of 

```
!self.ErrMsg.nil?
```

I can't push the change, so if agreed, I'd appreciate it if someone could do it

**Comment by valsavva** [comment]
blank? is no available because ActiveRecord is not a dependency in this project. I fixed the error in an alternative way and published a new version - please update the gem. Thanks for your help.
