### ISSUE TITLE
Capital IQ deprecating SSLv3 tonight

### ISSUE THREAD

**Issue by jdesmont** [exitround/capital-iq#2]
cf. Capital IQ's email: << For security purposes, we have upgraded our S&P Capital IQ API platforms to require TLS (TLSv1) security protocol for access.  As of February 6th, 2016 you will no longer be able to connect to any of our S&P Capital IQ API platform services using the older less secure SSL (SSLv3) security protocol. >>

Looks like your gem is using SSLv3. cf.

```
response_data = from_cache(request_body) || self.class.post(
          ENDPOINT, body: request_body, basic_auth: @auth, ssl_version: :SSLv3
      ).parsed_response
```

but there may be other places too.

**Comment by valsavva** [comment]
This is the only place. Fixed.
